---
title: "Replication - Main Tables"
output:
  pdf_document: default
  html_document: default
date: "2025-06-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Replication of the main tables


## Table 1 - Incumbent 2010

Packages to install if not done already.

```{r}
install.packages(c("tidyverse","stargazer","knitr","broom","haven","fixest","modelsummary","gt","webshot2"))
```

Required libraries.

```{r}
library(tidyverse)
library(stargazer)
library(knitr)
library(broom)
library(haven)
library(fixest)
library(modelsummary)
library(gt)
library(webshot2)
```

Macros, controls, and sample selection.

```{r}
# Defining the control variables
gpcontrols <- c("GP_population", "GP_lit", "GP_sc", "GP_st", "GP_nbvillages", 
                "RES00_gender", "RES00_obc", "RES00_sc", "RES00_st", 
                "RES10_obc", "RES10_sc", "RES10_st", "RES05_obc", "RES05_sc", "RES05_st")

# Defining the dependent variables
incum_dep_vars1 <- c("INC05_running", "INC05_voteshare", "INC05_won", 
                     "INCSPOUSE05_running", "INCSPOUSE05_voteshare", "INCSPOUSE05_won",
                     "INCOTHER05_running", "INCOTHER05_voteshare", "INCOTHER05_won",
                     "INCorFAM05_running", "INCorFAM05_voteshare", "INCorFAM05_won")

# Loading the data
# Change the path if necessary.
data <- read_dta("~/work/Electoral data cleaned.dta")

# Filtering the data (keeping non-reserved GPs, and only 1 observation)
data_filtered <- data %>%
  filter(RES10_gender == 0 & SAMPLE_hhsurvey == 1 & GP_tag == 1 & INC05_can_run == 1) %>%
  mutate(
    FAMnotINC05_running = INCorFAM05_running - INC05_running,
    FAMnotINC05_voteshare = INCorFAM05_voteshare - INC05_voteshare,
    FAMnotINC05_won = INCorFAM05_won - INC05_won
  )
```

Model estimation.

```{r}
# Function for the regression formulas
create_formula <- function(dep_var, model_type) {
  base_controls <- paste(gpcontrols, collapse = " + ")
  
  if (model_type == "any_treatment") {
    formula_str <- paste(dep_var, "~ INT_treatment + RES05_gender + X_anytr_genderres05 +", 
                         base_controls, "+ factor(district)")
  } else if (model_type == "gender_general") {
    formula_str <- paste(dep_var, "~ INT_treatment_gender + INT_treatment_general + RES05_gender +",
                         "X_generaltr_genderres05 + X_gendertr_genderres05 +", 
                         base_controls, "+ factor(district)")
  }
  
  return(as.formula(formula_str))
}

# Function for the statistical tests
calculate_tests <- function(model, model_type) {
  if (model_type == "any_treatment") {
    # Test: RES05_gender + X_anytr_genderres05 = 0
    test1 <- car::linearHypothesis(model, "RES05_gender + X_anytr_genderres05 = 0")
    pval1 <- test1$`Pr(>F)`[2]
    
    # Test: INT_treatment = RES05_gender
    test2 <- car::linearHypothesis(model, "INT_treatment - RES05_gender = 0")
    pval2 <- test2$`Pr(>F)`[2]
    
    return(list(pval1 = round(pval1, 2), pval2 = round(pval2, 2)))
    
  } else if (model_type == "gender_general") {
    # Test: INT_treatment_gender = INT_treatment_general
    test1 <- car::linearHypothesis(model, "INT_treatment_gender - INT_treatment_general = 0")
    pval1 <- test1$`Pr(>F)`[2]
    
    # Test: INT_treatment_gender + X_gendertr_genderres05 = INT_treatment_general + X_generaltr_genderres05
    test2 <- car::linearHypothesis(model, 
                                   "INT_treatment_gender + X_gendertr_genderres05 - INT_treatment_general - X_generaltr_genderres05 = 0")
    pval2 <- test2$`Pr(>F)`[2]
    
    return(list(pval1 = round(pval1, 2), pval2 = round(pval2, 2)))
  }
}

# Estimating the models
models_list <- list()
control_means <- list()
test_results <- list()


### Models with "any treatment" 
for (i in 1:length(incum_dep_vars1)) {
  dep_var <- incum_dep_vars1[i]
  
  # control mean
  control_mean <- data_filtered %>%
    filter(INT_treatment == 0 & RES05_gender == 0) %>%
    summarise(mean = mean(!!sym(dep_var), na.rm = TRUE)) %>%
    pull(mean) %>%
    round(2)
  
  control_means[[i]] <- control_mean
  
  # model estimate
  formula <- create_formula(dep_var, "any_treatment")
  model <- lm(formula, data = data_filtered)
  models_list[[i]] <- model
  
  # statistical tests
  test_results[[i]] <- calculate_tests(model, "any_treatment")
}

### Models with "gender and general treatment" 
for (i in 1:length(incum_dep_vars1)) {
  dep_var <- incum_dep_vars1[i]
  j <- i + length(incum_dep_vars1)
  
  # control mean
  control_means[[j]] <- control_means[[i]]
  
  # model estimate
  formula <- create_formula(dep_var, "gender_general")
  model <- lm(formula, data = data_filtered)
  models_list[[j]] <- model
  
  # statistical tests
  test_results[[j]] <- calculate_tests(model, "gender_general")
}

```

Table.

```{r}
# variables to display
outregvar2 <- c("INT_treatment", "INT_treatment_gender", "INT_treatment_general")

# colnames
col_names <- c(
  paste("Any Treat", 1:12),
  paste("Gender/General", 1:12)
)

# additional lines for means and test results!
additional_lines <- list(
  c("District FE", rep("Yes", length(models_list))),
  c("GP Controls", rep("Yes", length(models_list))),
  c("Mean in Control not WR in 2005", unlist(control_means)),
  c("Test Treat Effect in WR=0", sapply(test_results, function(x) x$pval1))
)

# generate table
stargazer(models_list,
          type = "text",  
          column.labels = col_names,
          keep = outregvar2,
          add.lines = additional_lines,
          digits = 2,
          title = "Table 1: Effects on Incumbent and Family Candidate Entry (2005)",
          out = "Table1_Incumbent_2010.txt")

```


## Table 2 - Performance 2010

```{r}
# Libraries
library(tidyverse)
library(fixest)
library(stargazer)
library(haven)
library(lmtest)
```

```{r}
# ## DEFINITION OF THE MACROS ## #

# Control variables
gpcontrols <- c("GP_population", "GP_lit", "GP_sc", "GP_st", "GP_nbvillages",
                "RES00_gender", "RES00_obc", "RES00_sc", "RES00_st",
                "RES10_obc", "RES10_sc", "RES10_st", "RES05_obc", "RES05_sc", "RES05_st")

gpcontrols15 <- c(gpcontrols, "RES15_obc", "RES15_sc", "RES15_st")

# Regression variables
outregvar2 <- c("INT_treatment", "RES05_gender", "X_anytr_genderres05")
```

```{r}
# ## DATA PROCESSING ## #

# Loading the data. Change path accordingly to your workspace.
data <- read_dta("~/work/Electoral data cleaned.dta")

# Filtering the data
data_filtered <- data %>%
  filter(RES10_gender == 0, SAMPLE_hhsurvey == 1, GP_tag == 1, INC05_can_run == 1) %>%
  mutate(
    FAMnotINC05_running = INCFAM05_running - INC05_running,
    FAMnotINC05_voteshare = INCFAM05_voteshare - INC05_voteshare,
    FAMnotINC05_won = INCFAM05_won - INC05_won
  )

# Generate the PERFORMANCE INDICES of the program

# Explanation: used variables to build the indices are the data related to the success of implementation of the NREGA program.
# Standardized measures about: participation, satisfied demand, waiting time, work done in the frame of the program. 
data_filtered <- data_filtered %>%
  mutate(
    # index_empl_svy_0 participation, unmet demand (men and women)
    index_empl_svy_0 = rowMeans(select(., std_HH_NREGA, std_HH_NREGA_unmet_demand_m, std_HH_NREGA_unmet_demand_f), na.rm = TRUE),
    # index_empl_svy_1 unmet demand, waiting time, and work provided within the NREGA (men and women)
    index_empl_svy_1 = rowMeans(select(., std_HH_NREGA_unmet_demand, std_HH_NREGA_unmet_demand_m, std_HH_NREGA_unmet_demand_f, std_HH_NREGA_waiting_time_m, std_HH_NREGA_waiting_time_f, std_HH_NREGA, std_HH_NREGA_work_m, std_HH_NREGA_work_f), na.rm = TRUE),
    # index_empl_svy_2 work provided (men and women)
    index_empl_svy_2 = rowMeans(select(., std_HH_NREGA, std_HH_NREGA_work_m, std_HH_NREGA_work_f), na.rm = TRUE),
    # index_empl_svy_3 unmet demand (men and women)
    index_empl_svy_3 = rowMeans(select(., std_HH_NREGA_unmet_demand_m, std_HH_NREGA_unmet_demand_f), na.rm = TRUE)
  )

# Dependent variables
incum_dep_vars1 <- c("INC05_running", "INC05_voteshare", "INC05_won",
                     "INCSPOUSE05_running", "INCSPOUSE05_voteshare", "INCSPOUSE05_won",
                     "INCOTHER05_running", "INCOTHER05_voteshare", "INCOTHER05_won")

indices <- c("index_empl_svy_1")

```

```{r}
# Starting lists to stock the upcoming results
models_list <- list()
control_means <- numeric(length(incum_dep_vars1) * length(indices))
pvals_1 <- numeric(length(incum_dep_vars1) * length(indices))
pvals_2 <- numeric(length(incum_dep_vars1) * length(indices))
effect_average <- numeric(length(incum_dep_vars1) * length(indices))
effect_good <- numeric(length(incum_dep_vars1) * length(indices))
effect_bad <- numeric(length(incum_dep_vars1) * length(indices))
```

```{r}
# ## DOING THE REGRESSIONS ## #

i <- 0
for (x in 0:1) {
  for (dep_var in incum_dep_vars1) {
    for (index in indices) {
      i <- i + 1
      
      # control mean
      control_mean <- data_filtered %>%
        filter(INT_treatment == 0 & RES05_gender == x) %>%
        summarise(mean = mean(!!sym(dep_var), na.rm = TRUE)) %>%
        pull(mean) %>%
        round(2)
      
      control_means[i] <- control_mean
      
      # mean and standard error of the index
      index_stats <- data_filtered %>%
        filter(RES05_gender == x) %>%
        summarise(mean = mean(!!sym(index), na.rm = TRUE),
                  sd = sd(!!sym(index), na.rm = TRUE))
      
      index_mean <- round(index_stats$mean, 2)
      index_sd <- round(index_stats$sd, 2)
      
      # interaction variables
      # explanation: interactions between performance at the time and gender of the incumbent in 2005 and treatment
      # helps evaluating how the treatment effects vary depending on the gender and the performance of the incumbent
      data_filtered <- data_filtered %>%
        mutate(
          TEMP_index = get(index),
          TEMP_X_res_index = RES05_gender * get(index),
          TEMP_X_anytr_index = INT_treatment * get(index),
          TEMP_X_anytr_res_index = INT_treatment * RES05_gender * get(index)
        )
      
      # checking that all the variables exist in the set
      all_vars <- c(dep_var, "INT_treatment", "TEMP_index", "TEMP_X_anytr_index", gpcontrols, "district")
      if (all(all_vars %in% names(data_filtered))) {
        # model estimation
        formula <- as.formula(paste(dep_var, "~ INT_treatment + TEMP_index + TEMP_X_anytr_index +", paste(gpcontrols, collapse = " + "), "+ factor(district)"))
        model <- tryCatch({
          lm(formula, data = data_filtered %>% filter(RES05_gender == x))
        }, error = function(e) {
          message("Error in model fitting: ", e$message)
          NULL
        })
        
        if (!is.null(model)) {
          models_list[[i]] <- model
          
          # doing the tests
          test_1 <- tryCatch({
            waldtest(model, c("INT_treatment + TEMP_X_anytr_index" = 0, paste("TEMP_index", index_mean, sep = " = ")))
          }, error = function(e) {
            message("Error in test 1: ", e$message)
            NULL
          })
          
          if (!is.null(test_1)) {
            pvals_1[i] <- round(test_1$p.value, 2)
          } else {
            pvals_1[i] <- NA
          }
          
          test_2 <- tryCatch({
            waldtest(model, c("INT_treatment + TEMP_X_anytr_index" = 0))
          }, error = function(e) {
            message("Error in test 2: ", e$message)
            NULL
          })
          
          if (!is.null(test_2)) {
            pvals_2[i] <- round(test_2$p.value, 2)
          } else {
            pvals_2[i] <- NA
          }
          
          # effects
          effect_average[i] <- coef(model)["INT_treatment"] + coef(model)["TEMP_X_anytr_index"] * index_mean
          effect_good[i] <- coef(model)["INT_treatment"] + coef(model)["TEMP_X_anytr_index"] * (index_mean + index_sd)
          effect_bad[i] <- coef(model)["INT_treatment"] + coef(model)["TEMP_X_anytr_index"] * (index_mean - index_sd)
          
          # displaying said effects
          cat("Effects on outcome", dep_var, "\n")
          cat("Effect of treatment for average performing incumbent is", effect_average[i], "\n")
          cat("Effect of treatment for +1 sd performing incumbent is", effect_good[i], "\n")
          cat("Effect of treatment for -1 sd performing incumbent is", effect_bad[i], "\n")
        } else {
          message("Model fitting failed for ", dep_var)
        }
      } else {
        message("Some variables are missing in the dataset for ", dep_var)
      }
    }
  }
}

```

```{r}
# ## GENERATING THE OUTPUT TABLE ## #

stargazer(models_list,
          type = "text",
          column.labels = paste("Model", 1:length(models_list)),
          keep = c("INT_treatment", "TEMP_index", "TEMP_X_anytr_index"),
          add.lines = list(
            c("District FE", rep("Yes", length(models_list))),
            c("GP Controls", rep("Yes", length(models_list))),
            c("Mean in Control not WR in 2005", control_means),
            c("Test Treat Effect", pvals_1),
            c("Test Perf Effect in Treat", pvals_2)
          ),
          digits = 2,
          title = "Table 2: Performance - 2010",
          # change output path accordingly to your workspace
          out = file.path("~/work/Rajasthan-Voters-Replication/Table2_Performance_2010.txt"))

```



## Table 3 - Challengers 2010

## Table 4- Candidates 2015


```{r}
# Packages to install if necessary
install.packages(c("tidyverse", "haven", "fixest","stargazer"))
#Libraries
library(tidyverse)
library(fixest)
library(stargazer)
library(haven)



## MACROS

# Controls
gpcontrols <- c("GP_population", "GP_lit", "GP_sc", "GP_st", "GP_nbvillages",
                "RES00_gender", "RES00_obc", "RES00_sc", "RES00_st",
                "RES10_obc", "RES10_sc", "RES10_st", "RES05_obc", "RES05_sc", "RES05_st")

gpcontrols15 <- c(gpcontrols, "RES15_obc", "RES15_sc", "RES15_st")

# Regression variables
outregvar2 <- c("INT_treatment", "RES05_gender", "X_anytr_genderres05")


## DATA PROCESSING 

# Loading the data. Change path depending on your workspace.
data <- read_dta("~/work/Electoral data 2015 cleaned.dta")

# Filtering the data
data_filtered <- data %>%
  filter(RES10_gender == 0, GP_tag == 1, RES15_gender == 0) %>%
  mutate(
    INC10_can_run = 1,
    INC10_can_run = ifelse(ELEC10_won_female == 0 & RES15_gender == 1, 0, INC10_can_run),
    INC10_can_run = ifelse(ELEC10_won_sc == 0 & RES15_sc == 1, 0, INC10_can_run),
    INC10_can_run = ifelse(ELEC10_won_st == 0 & RES15_st == 1, 0, INC10_can_run)
  )

# Generate new variables
for (var in c("INT_treatment", "X_anytr_genderres05", "RES05_gender")) {
  data_filtered <- data_filtered %>%
    mutate(!!paste0("X15_", var) := get(var) * (RES15_gender == 1))
}

outregvar15 <- c("INT_treatment", "RES05_gender", "X_anytr_genderres05", "RES15_gender",
                 "X15_INT_treatment", "X15_RES05_gender", "X15_X_anytr_genderres05")

# Dependent variables
dep_vars <- c("ELEC15_nbcands", "ELEC15_incum10_running", "ELEC15_voteshare_incum10",
              "ELEC15_prop_cand2010", "ELEC15_voteshare_cand2010", "ELEC15_prop_female",
              "ELEC15_voteshare_female", "ELEC15_prop_nongen", "ELEC15_voteshare_nongen")

```


```{r}
# List to stock the results:
models_list <- list()
control_means <- numeric(length(dep_vars))
pvals <- numeric(length(dep_vars))
```

```{r}
## DOING THE REGRESSIONS


for (i in seq_along(dep_vars)) {
  dep_var <- dep_vars[i]
  
  # control mean
  control_mean <- data_filtered %>%
    filter(INT_treatment == 0 & RES05_gender == 0) %>%
    summarise(mean = mean(!!sym(dep_var), na.rm = TRUE)) %>%
    pull(mean) %>%
    round(2)
  
  control_means[i] <- control_mean
  
  # model estimation
  formula <- as.formula(paste(dep_var, "~", paste(c(outregvar2, gpcontrols15), collapse = " + "), "+ factor(district)"))
  model <- lm(formula, data = data_filtered)
  models_list[[i]] <- model
  
  # do the test
  test_result <- summary(lm(test = RES05_gender + X_anytr_genderres05, data = model$model))$coefficients[2, 4]
  pvals[i] <- round(test_result, 2)
}

```

```{r}
stargazer(models_list,
          type = "text",
          column.labels = paste("Model", 1:length(dep_vars)),
          keep = outregvar2,
          add.lines = list(
            c("District FE", rep("Yes", length(dep_vars))),
            c("GP Controls", rep("Yes", length(dep_vars))),
            c("Mean in Control not WR in 2015", control_means),
            c("Test Treat Effect in WR=Treat Effect in NWR", pvals)
          ),
          digits = 2,
          title = "Table 4: Effects on Candidates - 2015",
          out = file.path("~/work/Rajasthan-Voters-Replication/Table4_Candidates_2015.txt"))

```


## Table 5 - Voters perception

